azure:
  key: azureKey
aws:
  key: awsKey
google:
  key: googleKey
on_premises:
  ip: ip-address
project_config: yes
base_package: com.example.backend
provider: AZURE
infrastructure: SERVERLESS #TRADITIONAL #MICROSERVICES #SERVERLESS
authentication: none
functions:
  function_1:
      provider: AWS
      authentication: none
  function_2:
    provider: AZURE
    authentication: none