name: Maven Build and Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Add dependency
        run: mvn install:install-file -Dfile="src/main/resources/library-0.0.6.jar" -DgroupId="io.github.masterarbeit-2023" -DartifactId="library" -Dversion="0.0.6" -Dpackaging="jar"

      - name: Build with Maven
        run: mvn clean install

      - name: Move jar file
        run: mv target/backend-0.0.1-SNAPSHOT.jar .

      - name: Run JAR file
        run: sudo java -jar backend-0.0.1-SNAPSHOT.jar

