name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run script file
      run: |
          chmod +x ./public/scripts/test.sh
          ./public/scripts/test.sh
      shell: bash

    - name: Modify files
      run: |
        # Modify files here
        echo "New content" > file.txt
